### ISSUE TITLE
og.url is not mapped

### ISSUE THREAD

**Issue by anuragdhingra** [otiai10/opengraph#11]
@otiai10 
In the current implementation, `opengraph.URL` defaults to the parsed request URL and doesn't maps the `og.url` meta tag.
Is it okay to add a new field called `Value` in `opengraph.URL` struct which maps the `og.url` meta tag value?

Or if I am missing something here, please let me know. I want fetch the `og.url` meta tag from the parsed HTML.
Thank you.

**Comment by otiai10** [comment]
ah... nice catch. You caught the problem correctly. Thank you.

If `og:url` exists, it should be preferred over the `URL` which is parsed from initial input.
Thus, we don't need `Value` field in `opengraph.URL`, but just overwrite it if `og:url` exists.

What do you think?

**Comment by anuragdhingra** [comment]
The reason I would prefer a different value is that if `og.URL` is overwritten we won't have any clear mechanism to know if it was fetched from the meta tag or is the default value. Also, I believe maybe passing the value as `string` instead of `URL` would be better due to validity issues. What do you think?

**Comment by otiai10** [comment]
What kind of validity do you mean?

**Comment by anuragdhingra** [comment]
> What kind of validity do you mean?
If the content/URL set on `og:url` meta property is invalid then parsing it might cause an error which might not be what we want maybe? Just returning back the content fetched from the property as `string` should be okay acc. to me.

Also, if we overrite it do we have any way to check if `og.url` property was found or not?

**Comment by anuragdhingra** [comment]
Closing this now. Thank you!
