### ISSUE TITLE
Fetching `og:description` defaults to <meta name="description"> if not found

### ISSUE THREAD

**Issue by anuragdhingra** [otiai10/opengraph#13]
@otiai10 
Fetching `og:description` defaults to `<meta name="description">` if not found.
Current implementation has this `case m.IsDescription() && og.Description == ""`, is it a spec or bug?

If its a spec, do you think we can avoid that somehow or make the fallback mechanism optional, if `og:description` is not found? [here](https://github.com/otiai10/opengraph/blob/2c56ab07d168db78ae7c66901c837adf7a2ed50d/tag_meta.go#L40) 

Thank you!

**Comment by anuragdhingra** [comment]
@otiai10 any resolutions or ideas you might have to solve the above problem? Thank you.

**Comment by otiai10** [comment]
I checked this document https://ogp.me/ and
IMO, it should prefer `og:description` rather than `description`.

**Comment by otiai10** [comment]
Defaulting to `<meta name="description" />` makes sense,  but `og:description` should be preferred.

**Comment by otiai10** [comment]
Closed by #21
