### ISSUE TITLE
[Feature Request] User-Agent Option

### ISSUE THREAD

**Issue by go-u** [otiai10/opengraph#7]
Hello OCHIAI,
@otiai10 

Thank you for very nice app. This post is about feature request and who will code it ?

**[ Why User-Agent Option ? ]**
Some web sites are rendering OGP Tags Dynamically with javascript.
But javascript don't work in simple crawler like twitter bot or this golang app.

So, many web sites are rendering OGP Meta tag on server side.
Popular way is SSR(Node.js), But more easier way is "[Prerendering with Netlify](https://docs.netlify.com/site-deploys/post-processing/prerendering/)"

But Netlify check User-Agent for prerendering. **So this app can't get OGP meta tags.** 
[[Common Issue] Understanding and debugging prerendering](https://community.netlify.com/t/common-issue-understanding-and-debugging-prerendering/150) 
 (I think potentially other sites check User-Agent too, for reduce rendering cost)

**[ Who code it ? ]**
I'm not professional. But If you are wellcome pull request about this feature, I want to write code.
But if you don't want to merge this feature or you want to code your ownself, I don't send pull request.
So, please tell me your feelings.

Thanks,

**Comment by otiai10** [comment]
Thx, could you give me example web pages which I can debug on

**Comment by otiai10** [comment]
This is my workaround, anyway

```go
	buf := bytes.NewBuffer(nil)
	req, err := http.NewRequest("GET", "https://ua-check-site.io/", buf)
	if err != nil {
		log.Fatalln(1001, err)
	}

	const ua = "Mozilla/5.0"
	req.Header.Add("User-Agent", ua)

	res, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatalln(1002, err)
	}

	ogp := opengraph.New("https://ua-check-site.io/")
	if err := ogp.Parse(res.Body); err != nil {
		log.Fatalln(1003, err)
	}

	fmt.Printf("%+v\n", ogp)
```

**Comment by go-u** [comment]
Thanks for showing the detailed code.
The workaround works perfectly.

Thank you very much.
