### ISSUE TITLE
Only parse meta tags?

### ISSUE THREAD

**Issue by anuragdhingra** [otiai10/opengraph#9]
@mbleigh @otiai10 
Hey, I went through the implementation and seems like the fetch method parses `title` `meta` and `link` elements to create the `opengraph` object. Any way I could just check for meta tags?

**Comment by otiai10** [comment]
@anuragdhingra 
Is this what you want? https://github.com/otiai10/opengraph/pull/10

**Comment by anuragdhingra** [comment]
Yep, exactly. Thank you!

**Comment by otiai10** [comment]
will merge. Thx for your feedback

**Comment by anuragdhingra** [comment]
@otiai10 Thank you for quick response. 
Just a suggestion maybe if we could pass an optional policy to the `Fetch` method, it would make the method more flexible and avoid the need to use `New` and `Parse`, what do you think? 
If no policy is passed maybe it can use some default policy that includes everything.

**Comment by anuragdhingra** [comment]
If it sounds okay to you, I can send a PR for the same. TIA.

**Comment by otiai10** [comment]
Thanks. Sure you can send it.

By the way, I'm planning to release v2.0 coz I don't like the current interface of `New`, `Fetch`, and `FetchWithContext` as they are now.
